
package:
  name: myext
  version: 1.0.0

source:
  path: ..

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - wheel
    - swig
    - epics-base
  run:
    - python

build:
  script: python setup.py build_ext install --single-version-externally-managed --record=record.txt

test:
  imports:
    - myext.myfunc

about:
  license: BSD
