name: "Build Conda Packages"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  build:
    name: conda build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Debug paths
        shell: bash -l {0}
        run: |
            printenv
            pwd
            ls
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          conda-build-version: 3
      - name: Setup Xcode and SDK on macOS
        if: runner.os == 'macOS'
        shell: bash -l {0}
        run: |
            CONDA_BUILD_SYSROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
            [[ -e /opt/MacOSX10.9.sdk ]] || sudo ln -s ${CONDA_BUILD_SYSROOT} /opt/MacOSX10.9.sdk
            printf "CONDA_BUILD_SYSROOT:\n    - ${CONDA_BUILD_SYSROOT}\n" >> conda-recipe/conda_build_config.yaml
            sudo xcode-select -s "/Applications/Xcode_11.7.app"
            echo "DEVELOPER_DIR=/Applications/Xcode_11.7.app/Contents/Developer" >> $GITHUB_ENV
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Build
        if: env.RUNNER_OS != 'Linux'
        shell: bash -l {0}
        run: | 
            mkdir packages
            conda build --output-folder packages conda-recipe
      - name: Build
        if: env.RUNNER_OS == 'Linux'
        shell: bash -l {0}
        run: |
            mkdir packages
            .scripts/conda_build_in_docker.sh conda-recipe packages
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: packages/*/*.tar.bz2
          retention-days: 1
