name: "Build Conda Packages"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  Linux:
    name: conda build in conda-forge-anvil docker
    runs-on: "ubuntu-latest"
    container: condaforge/linux-anvil:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Build
        shell: bash -l {0}
        run: |
            ls
            pwd
            mkdir packages
            conda build --output-folder packages conda-recipe
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: packages/*/*.tar.bz2
          retention-days: 1
  macOS:
    name: conda build
    runs-on: "macos-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          conda-build-version: 3
      - name: Setup Xcode and SDK
        shell: bash -l {0}
        run: |
            sudo xcode-select -s "/Applications/Xcode_11.7.app"
            CONDA_BUILD_SYSROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
            [[ -e /opt/MacOSX10.9.sdk ]] || sudo ln -s ${CONDA_BUILD_SYSROOT} /opt/MacOSX10.9.sdk
            printf "CONDA_BUILD_SYSROOT:\n    - ${CONDA_BUILD_SYSROOT}\n" >> conda-recipe/conda_build_config.yaml
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Build
        shell: bash -l {0}
        run: | 
            mkdir packages
            conda build --output-folder packages conda-recipe
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: packages/*/*.tar.bz2
          retention-days: 1
