name: "Build Conda Packages"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: conda build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump env
        run: |
            printenv
            echo "USER_ID=$(id -u)" >> $GITHUB_ENV
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          conda-build-version: 3
      - name: Setup Xcode and SDK on macOS
        if: runner.os == 'macOS'
        run: |
            sudo xcode-select -s "/Applications/Xcode_11.7.app"
            CONDA_BUILD_SYSROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
            [[ -e /opt/MacOSX10.9.sdk ]] || sudo ln -s ${CONDA_BUILD_SYSROOT} /opt/MacOSX10.9.sdk
            printf "CONDA_BUILD_SYSROOT:\n    - ${CONDA_BUILD_SYSROOT}\n" >> conda-recipe/conda_build_config.yaml
      - name: Activate conda
        run: |
            conda install anaconda-client
            conda info
      - name: Build ${{ runner.os }}
        if: runner.os == 'macOS'
        run: |
            mkdir packages
            conda build --output-folder packages conda-recipe
      - name: Build ${{ runner.os }}
        if: runner.os == 'linux'
        uses: docker://condaforge/linux-anvil:latest
        with:
            args: bash -c "whoami;id;ls -la /github/workspace;conda config --add channels defaults;conda info;cd /github/workspace;mkdir packages;conda build --output-folder packages conda-recipe"
        env:
          HOST_USER_ID: ${{ env.USER_ID }}
      - name: Upload Anaconda
        run: |
            conda activate test
            ls -la packages/*/*.tar.bz2
            id
            anaconda -v -t ${MY_CONDA_TOKEN} upload -l main --force packages/*/*.tar.bz2
        env:
            MY_CONDA_TOKEN: ${{ secrets.MY_CONDA_TOKEN }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: packages/*/*.tar.bz2
          retention-days: 1
